#!/usr/bin/env python3
"""Write mods/html/ent.c from WHATWG's entities.json:
    curl -sO https://html.spec.whatwg.org/entities.json
    python3 tools/htmlents.py entities.json > mods/html/ent.c
Each name once, without & and ;, sorted for a binary search, with whether
it is also recognised without its semicolon (the legacy ones)."""
import json, sys

d = json.load(open(sys.argv[1]))
names = {}
for k, v in d.items():
    nm = k[1:]
    semi = nm.endswith(";")
    nm = nm.rstrip(";")
    e = names.setdefault(nm, [v["characters"], 0])
    if not semi:
        e[1] = 1


def c(s):
    out = ""
    for b in s.encode("utf-8"):
        out += "\\x%02x" % b
    return out


rows = sorted(names.items(), key=lambda kv: kv[0].encode())
print('#include "hl.h"\n')
print("/* The HTML5 named character references, generated by tools/htmlents.py from")
print("   WHATWG's entities.json: name, characters, and whether the name is also")
print("   recognised with no semicolon. Sorted by name, byte by byte. */")
print("const hl_ent hl_ents[] = {")
for nm, (ch, leg) in rows:
    print('\t{ "%s", "%s", %d },' % (nm, c(ch), leg))
print("};\n")
print("const size_t hl_nents = sizeof hl_ents / sizeof hl_ents[0];")
