#!/usr/bin/env python3
"""Write mods/uni/tab.c from one version of the Unicode Character Database:

    tools/unigen.py fetch 15.1.0 build/ucd      # download what it reads
    python3 tools/unigen.py gen build/ucd > mods/uni/tab.c

Every table the uni module uses comes from the same version, recorded in
the output: bidi classes (DerivedBidiClass, which gives unassigned code
points their default class), mirrored pairs, bracket pairs, joining types,
the Arabic presentation forms a cell grid draws instead of shaping, and
display widths. The conformance tests in tests/uni come from the same
version; regenerate both together."""
import os, re, sys, urllib.request

FILES = ["UnicodeData.txt", "EastAsianWidth.txt", "ArabicShaping.txt",
         "BidiBrackets.txt", "BidiMirroring.txt", "extracted/DerivedBidiClass.txt",
         "BidiTest.txt", "BidiCharacterTest.txt"]
CLASSES = ["L", "R", "AL", "EN", "ES", "ET", "AN", "CS", "NSM", "BN", "B", "S",
           "WS", "ON", "LRE", "LRO", "RLE", "RLO", "PDF", "LRI", "RLI", "FSI", "PDI"]
JOIN = ["U", "R", "L", "D", "C", "T"]


def fetch(ver, out):
    os.makedirs(out, exist_ok=True)
    for f in FILES:
        dst = os.path.join(out, os.path.basename(f))
        if not os.path.exists(dst):
            urllib.request.urlretrieve(
                "https://www.unicode.org/Public/%s/ucd/%s" % (ver, f), dst)
    open(os.path.join(out, "VERSION"), "w").write(ver + "\n")


def lines(path):
    for l in open(path, encoding="utf-8"):
        l = l.split("#", 1)[0].strip()
        if l:
            yield [x.strip() for x in l.split(";")]


def rng(t):
    a, _, b = t.partition("..")
    return int(a, 16), int(b or a, 16)


def runs(vals):
    """Collapse {cp: value} into sorted (lo, hi, value) runs."""
    out = []
    for cp in sorted(vals):
        v = vals[cp]
        if out and out[-1][1] == cp - 1 and out[-1][2] == v:
            out[-1][1] = cp
        else:
            out.append([cp, cp, v])
    return out


def gen(d):
    ver = open(os.path.join(d, "VERSION")).read().strip()
    ud = {}
    first = None
    for f in lines(os.path.join(d, "UnicodeData.txt")):
        cp = int(f[0], 16)
        if f[1].endswith(", First>"):
            first = cp
            continue
        if f[1].endswith(", Last>"):
            for c in range(first, cp + 1):
                ud[c] = f
            continue
        ud[cp] = f

    bidi = {}
    for f in lines(os.path.join(d, "DerivedBidiClass.txt")):
        lo, hi = rng(f[0])
        for c in range(lo, hi + 1):
            bidi[c] = CLASSES.index(f[1])
    for c in range(0x110000):
        bidi.setdefault(c, 0)
    brun = [r for r in runs(bidi) if r[2] != 0]

    mirror = []
    for f in lines(os.path.join(d, "BidiMirroring.txt")):
        mirror.append((int(f[0], 16), int(f[1], 16)))
    mirror.sort()

    brackets = []
    for f in lines(os.path.join(d, "BidiBrackets.txt")):
        brackets.append((int(f[0], 16), int(f[1], 16), 1 if f[2] == "o" else 0))
    brackets.sort()

    join = {}
    for cp, f in ud.items():
        if f[2] in ("Mn", "Me", "Cf"):
            join[cp] = JOIN.index("T")
    for f in lines(os.path.join(d, "ArabicShaping.txt")):
        join[int(f[0], 16)] = JOIN.index(f[2])
    jrun = [r for r in runs(join) if r[2] != 0]

    forms = {}
    lig = {}
    tag = {"<isolated>": 0, "<final>": 1, "<initial>": 2, "<medial>": 3}
    for cp, f in ud.items():
        if not (0xFB50 <= cp <= 0xFDFF or 0xFE70 <= cp <= 0xFEFF):
            continue
        dec = f[5].split()
        if len(dec) < 2 or dec[0] not in tag:
            continue
        parts = [int(x, 16) for x in dec[1:]]
        if len(parts) == 1:
            forms.setdefault(parts[0], [0, 0, 0, 0])
            if not forms[parts[0]][tag[dec[0]]]:
                forms[parts[0]][tag[dec[0]]] = cp
        elif len(parts) == 2 and parts[0] == 0x0644 and dec[0] in ("<isolated>", "<final>") \
                and parts[1] in (0x0622, 0x0623, 0x0625, 0x0627):
            lig.setdefault(parts[1], [0, 0])[tag[dec[0]]] = cp

    width = {}
    for f in lines(os.path.join(d, "EastAsianWidth.txt")):
        if f[1] in ("W", "F"):
            lo, hi = rng(f[0])
            for c in range(lo, hi + 1):
                width[c] = 2
    for cp, f in ud.items():
        if f[2] in ("Mn", "Me") or (f[2] == "Cf" and cp != 0x00AD) or \
           0x1160 <= cp <= 0x11FF or cp == 0x200B:
            width[cp] = 0
    for c in list(range(0, 32)) + list(range(0x7F, 0xA0)):
        width[c] = 0
    wrun = [r for r in runs(width) if r[2] != 1]

    o = []
    o.append('#include "un.h"\n')
    o.append("/* Generated by tools/unigen.py from the Unicode Character Database %s;"
             % ver)
    o.append("   regenerate rather than edit. */\n")
    o.append('const char un_ucdver[] = "%s";\n' % ver)
    o.append("const un_rng un_bidi[] = {")
    o += ["\t{ 0x%04X, 0x%04X, %d }," % tuple(r) for r in brun]
    o.append("};\nconst size_t un_nbidi = sizeof un_bidi / sizeof *un_bidi;\n")
    o.append("const un_pair un_mirror[] = {")
    o += ["\t{ 0x%04X, 0x%04X }," % p for p in mirror]
    o.append("};\nconst size_t un_nmirror = sizeof un_mirror / sizeof *un_mirror;\n")
    o.append("const un_brk un_brack[] = {")
    o += ["\t{ 0x%04X, 0x%04X, %d }," % b for b in brackets]
    o.append("};\nconst size_t un_nbrack = sizeof un_brack / sizeof *un_brack;\n")
    o.append("const un_rng un_join[] = {")
    o += ["\t{ 0x%04X, 0x%04X, %d }," % tuple(r) for r in jrun]
    o.append("};\nconst size_t un_njoin = sizeof un_join / sizeof *un_join;\n")
    o.append("const un_form un_forms[] = {")
    o += ["\t{ 0x%04X, { 0x%04X, 0x%04X, 0x%04X, 0x%04X } }," % ((c,) + tuple(v))
          for c, v in sorted(forms.items())]
    o.append("};\nconst size_t un_nforms = sizeof un_forms / sizeof *un_forms;\n")
    o.append("const un_lig un_ligs[] = {")
    o += ["\t{ 0x%04X, 0x%04X, 0x%04X }," % ((c,) + tuple(v)) for c, v in sorted(lig.items())]
    o.append("};\nconst size_t un_nligs = sizeof un_ligs / sizeof *un_ligs;\n")
    o.append("const un_rng un_width[] = {")
    o += ["\t{ 0x%04X, 0x%04X, %d }," % tuple(r) for r in wrun]
    o.append("};\nconst size_t un_nwidth = sizeof un_width / sizeof *un_width;")
    print("\n".join(o))


def genwidth(d):
    """The core's width tables, src/wtab.c: zero width from 0x0300, wide from 0x1100."""
    ver = open(os.path.join(d, "VERSION")).read().strip()
    ud = {}
    first = None
    for f in lines(os.path.join(d, "UnicodeData.txt")):
        cp = int(f[0], 16)
        if f[1].endswith(", First>"):
            first = cp
            continue
        if f[1].endswith(", Last>"):
            for c in range(first, cp + 1):
                ud[c] = f
            continue
        ud[cp] = f
    zero = {}
    for cp, f in ud.items():
        if cp >= 0x0300 and (f[2] in ("Mn", "Me") or (f[2] == "Cf" and cp != 0x00AD)
                             or 0x1160 <= cp <= 0x11FF):
            zero[cp] = 1
    zero[0x200B] = 1
    wide = {}
    for f in lines(os.path.join(d, "EastAsianWidth.txt")):
        if f[1] in ("W", "F"):
            lo, hi = rng(f[0])
            for c in range(max(lo, 0x1100), hi + 1):
                if c not in zero:
                    wide[c] = 1
    o = ['#include "hibr.h"', '#include "pri.h"', "",
         "/* Generated by tools/unigen.py from the Unicode Character Database %s;" % ver,
         "   regenerate rather than edit. */", ""]
    both = dict((c, 0) for c in zero)
    both.update((c, 2) for c in wide)
    o.append("const struct rngw u8wtab[] = {")
    o += ["\t{ 0x%04X, 0x%04X, %d }," % tuple(r) for r in runs(both)]
    o.append("};")
    o.append("const size_t u8wtab_n = sizeof u8wtab / sizeof *u8wtab;")
    print("\n".join(o).rstrip())


if __name__ == "__main__":
    if len(sys.argv) == 4 and sys.argv[1] == "fetch":
        fetch(sys.argv[2], sys.argv[3])
    elif len(sys.argv) == 3 and sys.argv[1] == "gen":
        gen(sys.argv[2])
    elif len(sys.argv) == 3 and sys.argv[1] == "width":
        genwidth(sys.argv[2])
    else:
        sys.exit(__doc__)
